### ISSUE TITLE
package module entry is incorrect

### ISSUE THREAD

**Issue by naivefun** [DevimalPlanet/object-traversal#19]
`"module": "dist/lib.esm.js",` does not exist, is not usable for now, should be `object-traversal.esm.js`

https://github.com/DevimalPlanet/object-traversal/blob/161ce37a9a0e967fb57c0981c2fcb6b26ba29588/package.json#L5

**Comment by Devimal** [comment]
Thanks for the feedback. I have fixed it with the latest patch.
